# Generated by Django 5.1.4 on 2025-01-01 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exchanger", "0011_alter_transaction_exchange_rate"),
    ]

    operations = [
        migrations.CreateModel(
            name="SomBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
                ),
            ],
        ),
    ]
