# Generated by Django 5.1.4 on 2024-12-29 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exchanger", "0005_delete_transaction"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("currency", models.CharField(max_length=10)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=20)),
                ("exchange_rate", models.DecimalField(decimal_places=6, max_digits=10)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
