# Generated by Django 5.1.4 on 2024-12-29 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exchanger", "0006_transaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="exchange_rate",
            field=models.DecimalField(decimal_places=20, max_digits=50),
        ),
    ]
