# Generated by Django 5.1.4 on 2024-12-29 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exchanger", "0007_alter_transaction_exchange_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[("buy", "Покупка"), ("sell", "Продажа")],
                default="buy",
                max_length=8,
            ),
        ),
    ]
