# Generated by Django 5.1.4 on 2024-12-30 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exchanger", "0009_transaction_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="exchange_rate",
            field=models.DecimalField(decimal_places=5, max_digits=50),
        ),
    ]
