# Generated by Django 5.1.4 on 2024-12-30 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exchanger", "0010_alter_transaction_exchange_rate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="exchange_rate",
            field=models.DecimalField(decimal_places=2, max_digits=50),
        ),
    ]
